### ISSUE TITLE
ILM practical guide content (output 4.4) link is missing 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#13]
## Description
A clear and concise description of the problem.

## Steps To Reproduce

1. Go to https://terraso.org/guide/
2. Note Element 4.4 is missing in ILM elements and outputs section
## Expected behavior
<img width="482" alt="image" src="https://user-images.githubusercontent.com/92342777/207410802-9b4cb8d7-75f7-4052-ab17-a4867e0f7521.png">

**Comment by paulschreiber** [comment]
Added the link.
