### ISSUE TITLE
Use Plausible to track traffic to terraso and tools

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-wp-theme#14]
Two events for our brand new plausible tracker for Terraso.org 

## Description
Desired events:
* People navigate from Terraso.org to the application
* People click on ILM tools, tag for `element`, `output number`, `output name`, `tool name`

![image](https://user-images.githubusercontent.com/10799815/207920635-3b60b421-f22d-4eac-a05a-ad53dc43aa15.png)

![image](https://user-images.githubusercontent.com/10799815/207920795-5c62b32f-dd9e-4354-8db8-9c3f57c575e7.png)

**Comment by paulschreiber** [comment]
Outbound link clicks are enabled: https://plausible.io/terraso.org?goal=Outbound+Link%3A+Click

**Comment by DerekCaelin** [comment]
Plausible should track when people navigate to ILM tools, tag for `element`, `output number`, `output name`, `tool name`
