### ISSUE TITLE
Missing images in Help article, How to Draw Your Landscape Boundary

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#19]
## Description
Images are missing 
## Steps To Reproduce

1. Go to https://terraso.org/help/how-to-draw-your-landscape-boundary/
2. scroll down to step-by-step section.
3. Notice missing images 

## Expected behavior
Image appears next to the instruction. 

## Actual behavior
[screenshot ]
<img width="647" alt="image" src="https://user-images.githubusercontent.com/92342777/208786849-e426446f-ce83-40af-bf0b-ad386f6a74f0.png">

**Comment by DerekCaelin** [comment]
@paulschreiber I resolved this by going to the staging site, downloading the images, and re-uploading them.
