### ISSUE TITLE
Recent blog post link list shouldn't be displayed in the Help article

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#20]
## Description
Irrelevant content (e.g. Recent Posts component)  shows up in the Help article.

## Steps To Reproduce

1. Go to https://terraso.org/help/shared-files/ 
2. Notice 'Recent Posts' component on the right. 

## Expected behavior
The help article is dedicated to the topic like 'Add a new landscape to Terraso' article. 
https://terraso.org/help/add-a-new-landscape-to-terraso/

## Actual behavior
[Screenshot]
<img width="919" alt="image" src="https://user-images.githubusercontent.com/92342777/208788473-0f2655b8-ae15-4df0-81ec-8d48fdc6f0a2.png">

**Comment by DerekCaelin** [comment]
This was resolved by changing the template for the post.
