### ISSUE TITLE
Landscapes Map on Terraso Website links to Staging Site, not Production

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-wp-theme#42]
## Description
On the

## Steps To Reproduce

1. Go to URL: https://terraso.org/landscapes/
2. Look at map

## Expected behavior
See a map with about 20 locations.
<img width="933" alt="image" src="https://user-images.githubusercontent.com/10799815/236048999-cf20c1c0-11b6-455e-817c-0312622f2b3e.png">

## Actual behavior
See staging site data. 
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/10799815/236048703-99b9c5cf-8462-4063-a1a4-d2616f0fdebb.png">

**Comment by paulschreiber** [comment]
Fixed.
