### ISSUE TITLE
Change the button label to accommodate new visitors 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#5]
## Description
**CURRENT:** 
The call-to-action button on Homepage (https://terraso.org/) is optimized for the existing users with the big 'Log in' button in the Hero module. 
[Screenshot]
<img width="472" alt="image" src="https://user-images.githubusercontent.com/92342777/177787095-ed77e5ed-d25c-43cc-a6b2-04e87bffb47b.png">

**EXPECTED:** 
The CTA button label reads 'Sign up for Terraso' or 'Create Account' to guide the new users in addition to 'Log in' link as a secondary in the Hero module.

[Mockup]
<img width="579" alt="image" src="https://user-images.githubusercontent.com/92342777/177787234-6ab25bc3-9dd9-4ba1-827d-7fe162953287.png">

**Comment by paulschreiber** [comment]
@theladymay Can you update this and translate it?

**Comment by paulschreiber** [comment]
ES:
Sign up for - Regístrate por Terraso
Already a member - ¿Ya eres miembro?
Log in - Iniciar sesión

PT
Sign up for - Inscreva por Terraso
Already a member - Já é membro?
Log in - Entrar

FR
Sign up for - 
Already a member - 
Log in - Se connecter
