### ISSUE TITLE
Terraso iframe story map appears in blog post editor but not in published view

### ISSUE THREAD

**Issue by DerekCaelin** [techmatters/terraso-wp-theme#55]
## Description
Terraso story maps can be embedded by iframe. When I attempt to embed the iframe in a WP blog post, it seems to show up in the editor but does not appear in the preview or published post

Sample iframe
`<iframe src="https://app.staging.terraso.net/tools/story-maps/t8o6a8t/new-test-of-story-maps/embed" title="Terraso Story Map" width="750" height="500" frameborder="0"></iframe>`

## Steps To Reproduce

1. Start a wordpress blog post
2. Create an HTML code block
3. Insert iframe
4. See iframe appear in editor
5. click preview or  publish 
6. see issue

## Expected behavior
Iframe is visible in preview or published blog post

## Actual behavior
Iframe is not visible

## Additional context
The above iframe works in other wordpress websites

**Comment by paulschreiber** [comment]
iframes are currently restricted to administrator users.

**Comment by DerekCaelin** [comment]
this is resolved
