### ISSUE TITLE
Shared Files link appears odd

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#6]
## Description
Share Files link should have the same style as other articles, but appears differently. 
[Screenshot]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/92342777/177789361-b9339a98-1735-4ebe-b476-ad4ef21a4cbd.png">

## Steps To Reproduce

1. Go to URL:https://terraso.org/help/
2.Notice the Share files article link 

## Expected behavior
Share Files link shares the same style as other article links on the page.

**Comment by paulschreiber** [comment]
@Hanal-code the shared files link appears the same as other links
<img width="332" alt="image" src="https://user-images.githubusercontent.com/86784/206270017-0e06270c-608a-4368-97f7-f3e5a39ae914.png">
<img width="453" alt="image" src="https://user-images.githubusercontent.com/86784/206270059-21746b26-fb64-4dec-b43f-afc5c7ed633c.png">

Please specify what is different for you (color, size, underline, hover state, etc.).

**Comment by Hanal-code** [comment]
I guess it's no longer valid concern as there are many more links with the same style.
