### ISSUE TITLE
Remove Recent Posts  and Recent Comment modules on Help articles 

### ISSUE THREAD

**Issue by Hanal-code** [techmatters/terraso-wp-theme#77]
## Description
Help articles shouldn't display the blog post links or comments. 

## Steps To Reproduce

1. Go to URL: https://terraso.org/help/how-to-make-a-story-map/
2. Notice the unexpected right column filled with the blog links

## Expected behavior
No right column

## Actual behavior
<img width="1080" alt="image" src="https://github.com/techmatters/terraso-wp-theme/assets/92342777/49229228-103a-494b-8f71-57c059f352b3">

**Comment by paulschreiber** [comment]
Fixed with #84.
